# Generated by Django 5.1.3 on 2024-11-12 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../static/home/default.png', upload_to='profile_images/'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='../static/home/default.png', upload_to='group_images/')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(related_name='groups_user', to='home.group'),
        ),
        migrations.CreateModel(
            name='GroupMemberStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
            options={
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members_group', through='home.GroupMemberStatus', to='home.profile'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_chat_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post', to='home.group')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
